<?php

return [
    'grand-valley-empire' => [
        'name' => 'The Grand Green Valley',
        'slug' => 'grand-valley-empire',
        'pageTitle' => 'The Grand Green Valley  - BM Real Estate',
        'category' => 'Residential land / Plots',
        'detailPage' => 'property-details/grand-valley-empire.php',
        'heroImage' => 'images/featured-properties/grand-green-valley.jpg',
        'galleryImages' => [
            'images/featured-properties/grand-green-valley.jpg',
            'images/all-properties/grand-green2.jpg',
            'images/all-properties/grand-green3.jpg',
            // 'images/banner/banner-property-3.jpg',
        ],
        'summary' => 'A premium plotted township with modern planning, wide roads, and steady investment potential.',
        'description' => [
            'This society will have all basic facilities and amenities to suit homebuyer’s needs and requirements. Brought to you by RRR Infra Developers, RRR The Grand Green Valley is scheduled for possession in Jan, 2026.',
            'This housing society has multiple property options to offer, in varied price range, making it one of the most suitable address to own, that too in your budget.',
        ],
        'location' => 'Fatehabad Rd, near Dauki, Kundol, Agra, Uttar Pradesh 283111',
        'price' => 'On request',
        'priceSuffix' => '',
        'beds' => '3',
        'baths' => '2',
        'sqft' => '111 - 1000',
        'overviewId' => 'GVE-101',
        'nearby' => 'Located close to developing residential neighborhoods, main road access, and essential daily conveniences.',
        'nearbyItems' => [
            'Main road connectivity for city access and daily commute.',
            'Developing residential neighborhoods with future appreciation potential.',
            'Nearby grocery, pharmacy, and day-to-day utility stores.',
            'Schools and local services within convenient reach.',
        ],
        // 'overview' => [
        //     ['icon' => 'icon-house-line', 'label' => 'ID', 'value' => 'GVE'],
        //     ['icon' => 'icon-sliders-horizontal', 'label' => 'Type', 'value' => 'Plot'],
        //     ['icon' => 'icon-garage', 'label' => 'Garages', 'value' => '1'],
        //     ['icon' => 'icon-bed1', 'label' => 'Bedrooms', 'value' => '3 Rooms'],
        //     ['icon' => 'icon-bathtub', 'label' => 'Bathrooms', 'value' => '2 Rooms'],
        //     ['icon' => 'icon-crop', 'label' => 'Land Size', 'value' => '1150 SqFt'],
        //     ['icon' => 'icon-hammer', 'label' => 'Year Built', 'value' => '2024'],
        //     ['icon' => 'icon-ruler', 'label' => 'Size', 'value' => '1150 SqFt'],
        // ],
        'details' => [
            ['label' => 'ID', 'value' => '#GVE-101'],
            // ['label' => 'Beds', 'value' => '3'],
            ['label' => 'Price', 'value' => '₹ 15.55 - 50 L
'],
            ['label' => 'Year built', 'value' => 'Jan 2026'],
            ['label' => 'Size', 'value' => '1150 sqft'],
            ['label' => 'Type', 'value' => 'Plots + Villas'],
            // ['label' => 'Rooms', 'value' => '9'],
            ['label' => 'Status', 'value' => 'For sale'],
            // ['label' => 'Baths', 'value' => '2'],
            // ['label' => 'Garage', 'value' => '1'],
        ],
        // 'attachments' => [
        //     ['image' => 'images/home/file-1.png', 'name' => 'Grand-Valley-Empire-Brochure.pdf'],
        //     ['image' => 'images/home/file-2.png', 'name' => 'Grand-Valley-Empire-Price-List.pdf'],
        // ],
        'features' => [
            ['Club house', 'CCTV Camera', 'Gymnasium', 'Indoor Games', 'Kids Play Area'],
            ['Meditation area', 'Play area', 'Reserved parking', 'Security', 'Water storage'],
            ['Street lighting', 'jogging and scrolling track', 'Public transport access', 'Low-density planning', 'Secure township feel'],
        ],
        'map' => [
            'address' => 'Fatehabad Rd, near Dauki, Kundol, Agra',
            'city' => 'Agra',
            'state' => 'Uttar Pradesh',
            'postal' => '283111',
            'area' => '1150 sqft',
            'country' => 'India',
        ],
        'mapEmbed' => 'https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d56761.344381692485!2d78.17292!3d27.232207!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x39746f0075100abf%3A0x8cc9253ea6751170!2sAhinsa%20Green%20Valley!5e0!3m2!1sen!2sus!4v1775646395615!5m2!1sen!2sus',
        'websiteUrl' => 'https://ahinsagreenvalley.com/',
        'websiteLabel' => 'Click here for more details',
    ],
    'vrindavan-global' => [
        'name' => 'Vrindavan Global',
        'slug' => 'vrindavan-global',
        'pageTitle' => 'Vrindavan Global - BM Real Estate',
        'category' => 'Plots & Villas',
        'detailPage' => 'property-details/vrindavan-global.php',
        'heroImage' => 'images/featured-properties/vrindavan-global.jpg',
        'galleryImages' => [
            'images/featured-properties/vrindavan-global.jpg',
            'images/all-properties/vrindavan-global2.jpg',
            'images/all-properties/vrindavan-global3.jpg',
            // 'images/banner/banner-property-3.jpg',
        ],
        'summary' => 'A large township concept inspired by spiritual harmony and modern family living.',
        'description' => [
            'A landmark opportunity to own a piece of residential plot in Vrindavan in one of India’s most revered spiritual destinations. Set across a grand expanse of 65 acres, this thoughtfully master-planned community comprises 500 premium residential plots, each designed to offer peace, prosperity, and a deep connection with divinity. ',
            'offering flexibility for various lifestyle and investment goals — whether you dream of building a soulful retreat for your family, a second home for weekend escapes, or simply want to invest in an appreciating growth corridor.',
        ],
        'location' => 'Vrindavan, Mathura',
        'price' => 'On request',
        'priceSuffix' => '',
        'beds' => '3',
        'baths' => '2',
        'sqft' => '1400',
        'overviewId' => 'VG-204',
        'nearby' => 'Set near temple corridors, local markets, and future-ready access roads for easy movement.',
        'nearbyItems' => [
            '2.5 hours from Delhi',
            '1.5 hours from the upcoming Jewar Airport',
            'Seamless metro-city access',
            'Temple corridor, local markets, and daily conveniences nearby',
        ],
        // 'overview' => [
        //     ['icon' => 'icon-house-line', 'label' => 'ID', 'value' => 'VG-204'],
        //     ['icon' => 'icon-sliders-horizontal', 'label' => 'Type', 'value' => 'Farmhouse'],
        //     ['icon' => 'icon-garage', 'label' => 'Garages', 'value' => '1'],
        //     ['icon' => 'icon-bed1', 'label' => 'Bedrooms', 'value' => '3 Rooms'],
        //     ['icon' => 'icon-bathtub', 'label' => 'Bathrooms', 'value' => '2 Rooms'],
        //     ['icon' => 'icon-crop', 'label' => 'Land Size', 'value' => '0.09 Acres'],
        //     ['icon' => 'icon-hammer', 'label' => 'Year Built', 'value' => 'Jan, 2026'],
        //     // ['icon' => 'icon-ruler', 'label' => 'Size', 'value' => '65 Acer'],
        // ],
        'details' => [
            ['label' => 'ID', 'value' => '#VG-204'],
            // ['label' => 'Beds', 'value' => '3'],
            ['label' => 'Price', 'value' => 'On request'],
            ['label' => 'Year built', 'value' => '5 August 2025'],
            ['label' => 'Size', 'value' => '1500 sq.ft. to 3000 sq.ft.'],
            ['label' => 'Type', 'value' => 'residential plot'],
            // ['label' => 'Rooms', 'value' => '9'],
            ['label' => 'Status', 'value' => 'For sale'],
            // ['label' => 'Baths', 'value' => '2'],
            // ['label' => 'Garage', 'value' => '1'],
        ],
        // 'attachments' => [
        //     ['image' => 'images/home/file-1.png', 'name' => 'Vrindavan-Global-Brochure.pdf'],
        //     ['image' => 'images/home/file-2.png', 'name' => 'Vrindavan-Global-Price-List.pdf'],
        // ],
        'features' => [
            ['Childrens Play Area', 'Badminton Court', 'Banquet Hall'],
            ['Club House', 'Jogging Track', 'Indoor Gymnasium'],
            ['Temple corridor access', 'Local markets nearby', 'School access'],
        ],
        'map' => [
            'address' => 'NH19, Mathura-Vrindavan, Uttar Pradesh',
            'city' => 'Mathura',
            'state' => 'Uttar Pradesh',
            'postal' => '281121',
            'area' => '1500 sq.ft. to 3000 sq.ft.',
            'country' => 'India',
        ],
        'mapEmbed' => 'https://www.google.com/maps/embed?pb=!1m13!1m8!1m3!1d8393.108491262845!2d77.523709!3d27.537063!3m2!1i1024!2i768!4f13.1!3m2!1m1!2zMjfCsDMyJzEzLjQiTiA3N8KwMzEnMzQuNiJF!5e1!3m2!1sen!2sin!4v1775649476020!5m2!1sen!2sin',
        'websiteUrl' => 'https://hoablproject.com/index.html',
        'websiteLabel' => 'Click here for more details',
    ],
    'green-valley-empire' => [
        'name' => 'Green Valley Empire',
        'slug' => 'green-valley-empire',
        'pageTitle' => 'Green Valley Empire - BM Real Estate',
        'category' => 'Farmhouse',
        'detailPage' => 'property-details/green-valley-empire.php',
        'heroImage' => 'images/featured-properties/green-valley-empire.jpg',
        'galleryImages' => [
            'images/featured-properties/green-valley-empire.jpg',
            'images/all-properties/green-valley-empire2.jpg',
            'images/all-properties/green-valley-empire4.jpg',
            // 'images/all-properties/green-valley-empire2.jpg',
        ],
        'summary' => 'A thoughtfully designed community project with comfort, accessibility, and long-term value.',
        'description' => [
            'Green Valley Empire is a residential project under construction with a layout focused on everyday convenience and a calm neighborhood feel.',
            'The project blends organized development with a location that supports future residential growth and investment confidence.',
        ],
        'location' => 'Agra Road Corridor',
        'price' => 'On request',
        'priceSuffix' => '',
        'beds' => '3',
        'baths' => '2',
        'sqft' => '1325',
        'overviewId' => 'GVE-214',
        'nearby' => 'Conveniently positioned near schools, transport links, and everyday retail needs.',
        'nearbyItems' => [
            'All Connected Expressways',
            '1 hr 30 min to Jewar Airport',
            '5 min to Yamuna Expressway',
            '10 min to Lucknow Expressway',
            '30 min to Agra Airport',
            ' 25 min to Agra Cantt Railway Station',
        ],
        // 'overview' => [
        //     ['icon' => 'icon-house-line', 'label' => 'ID', 'value' => 'GVE-214'],
        //     ['icon' => 'icon-sliders-horizontal', 'label' => 'Type', 'value' => 'Farmhouse'],
        //     ['icon' => 'icon-garage', 'label' => 'Garages', 'value' => '1'],
        //     ['icon' => 'icon-bed1', 'label' => 'Bedrooms', 'value' => '3 Rooms'],
        //     ['icon' => 'icon-bathtub', 'label' => 'Bathrooms', 'value' => '2 Rooms'],
        //     ['icon' => 'icon-crop', 'label' => 'Land Size', 'value' => '1325 SqFt'],
        //     ['icon' => 'icon-hammer', 'label' => 'Year Built', 'value' => '2024'],
        //     ['icon' => 'icon-ruler', 'label' => 'Size', 'value' => '1325 SqFt'],
        // ],
        'details' => [
            ['label' => 'ID', 'value' => '#GVE-214'],
            // ['label' => 'Beds', 'value' => '3'],
            ['label' => 'Price', 'value' => 'On request'],
            ['label' => 'Year built', 'value' => 'Jan, 2026'],
            ['label' => 'Size', 'value' => '1325 sqft'],
            ['label' => 'Type', 'value' => 'Residential Plots'],
            // ['label' => 'Rooms', 'value' => '9'],
            ['label' => 'Status', 'value' => 'For sale'],
            // ['label' => 'Baths', 'value' => '2'],
            // ['label' => 'Garage', 'value' => '1'],
        ],
        // 'attachments' => [
        //     ['image' => 'images/home/file-1.png', 'name' => 'Green-Valley-Empire-Brochure.pdf'],
        //     ['image' => 'images/home/file-2.png', 'name' => 'Green-Valley-Empire-Price-List.pdf'],
        // ],
        'features' => [
            ['Childrens Play Area', '24X7 Water Supply', 'Temple'],
            ['24x7 Security', 'Internal Roads & Footpaths', '24x7 CCTV Surveillance'],
            ['Schools nearby', 'Medical support nearby', 'Retail convenience'],
        ],
        'map' => [
            'address' => 'Etmadpur–Khandoli Road, Mudi Chauraha, Agra',
            'city' => 'Agra',
            'state' => 'Uttar Pradesh',
            'postal' => '283202',
            'area' => '1325 SqFt',
            'country' => 'India',
        ],
        'mapEmbed' => 'https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d56761.344381692485!2d78.17292!3d27.232207!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x39746f0075100abf%3A0x8cc9253ea6751170!2sAhinsa%20Green%20Valley!5e0!3m2!1sen!2sus!4v1775646395615!5m2!1sen!2sus',
        'websiteUrl' => 'https://ahinsagreenvalley.com/',
        'websiteLabel' => 'Click here for more details',
    ],
    'upsic-project' => [
        'name' => 'The UPSIC Project',
        'slug' => 'upsic-project',
        'pageTitle' => 'The UPSIC Project - BM Real Estate',
        'category' => 'Farmhouse',
        'detailPage' => 'property-details/upsic-project.php',
        'heroImage' => 'images/featured-properties/upsic.jpg',
        'galleryImages' => [
            'images/featured-properties/upsic.jpg',
            'images/banner/banner-property-1.jpg',
            'images/banner/banner-property-2.jpg',
            // 'images/banner/banner-property-3.jpg',
        ],
        'summary' => 'A planned project built for secure investment with organized infrastructure and growth potential.',
        'description' => [
            'The UPSIC Project is an upcoming development planned to deliver structured plots and practical infrastructure in a strategic location.',
            'It is positioned for buyers looking for future-ready land with a straightforward development layout and strong accessibility.',
        ],
        'location' => 'Strategic Growth Zone, Agra',
        'price' => 'On request',
        'priceSuffix' => '',
        'beds' => '3',
        'baths' => '2',
        'sqft' => '1600',
        'overviewId' => 'UP-310',
        'nearby' => 'Close to developing civic infrastructure, road connections, and planned neighborhood services.',
        'nearbyItems' => [
            'Developing civic infrastructure in the nearby zone.',
            'Strong road network connections for quick access.',
            'Planned neighborhood services and utility growth.',
            'Retail and support services in the surrounding market.',
        ],
        // 'overview' => [
        //     ['icon' => 'icon-house-line', 'label' => 'ID', 'value' => 'UP-310'],
        //     ['icon' => 'icon-sliders-horizontal', 'label' => 'Type', 'value' => 'Farmhouse'],
        //     ['icon' => 'icon-garage', 'label' => 'Garages', 'value' => '1'],
        //     ['icon' => 'icon-bed1', 'label' => 'Bedrooms', 'value' => '3 Rooms'],
        //     ['icon' => 'icon-bathtub', 'label' => 'Bathrooms', 'value' => '2 Rooms'],
        //     ['icon' => 'icon-crop', 'label' => 'Land Size', 'value' => '1600 SqFt'],
        //     ['icon' => 'icon-hammer', 'label' => 'Year Built', 'value' => '2024'],
        //     ['icon' => 'icon-ruler', 'label' => 'Size', 'value' => '1600 SqFt'],
        // ],
        'details' => [
            ['label' => 'ID', 'value' => '#UP-310'],
            // ['label' => 'Beds', 'value' => '3'],
            ['label' => 'Price', 'value' => 'On request'],
            ['label' => 'Year built', 'value' => '2024'],
            ['label' => 'Size', 'value' => '1600 sqft'],
            ['label' => 'Type', 'value' => 'Farmhouse'],
            // ['label' => 'Rooms', 'value' => '9'],
            ['label' => 'Status', 'value' => 'For sale'],
            // ['label' => 'Baths', 'value' => '2'],
            // ['label' => 'Garage', 'value' => '1'],
        ],
        // 'attachments' => [
        //     ['image' => 'images/home/file-1.png', 'name' => 'UPSIC-Project-Brochure.pdf'],
        //     ['image' => 'images/home/file-2.png', 'name' => 'UPSIC-Project-Price-List.pdf'],
        // ],
        'features' => [
            ['Planned utilities', 'Accessible location', '24X7 Security', '24X7 Water Supply', ''],
            ['Investment-focused project', 'Good road access', 'Planned utilities', 'Secure development layout', 'Long-term asset value'],
            ['Nearby civic development', 'Retail support close by', 'Schools and services nearby', 'Low maintenance needs', 'Accessible location'],
        ],
        'map' => [
            'address' => 'Near Rambagh main Hathras road, Agra',
            'city' => 'Agra',
            'state' => 'Uttar Pradesh',
            'postal' => '282006',
            'area' => '1600 SqFt',
            'country' => 'India',
        ],
        'mapEmbed' => 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3556.9579156942015!2d78.04414161503943!3d27.210193882974807!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3974f0c97d3db1b3%3A0x0!2sAgra%2C%20Uttar%20Pradesh!5e0!3m2!1sen!2sin!4v1710000000003!5m2!1sen!2sin',
        'websiteUrl' => '#',
        'websiteLabel' => 'Click here for more details',
    ],
    'landmark-city' => [
        'name' => 'The Landmark City',
        'slug' => 'landmark-city',
        'pageTitle' => 'The Landmark City - BM Real Estate',
        'category' => 'Plot',
        'detailPage' => 'property-details/landmark-city.php',
        'heroImage' => 'images/featured-properties/landmark-city.jpg',
        'galleryImages' => [
            'images/featured-properties/landmark-city.jpg',
            'images/all-properties/landmark-city1.jpeg',
            'images/all-properties/landmark-city2.avif',
            // 'images/all-properties/landmark-city3.avif',
        ],
        'summary' => 'A modern plotted development with essential facilities and a family-friendly neighborhood concept.',
        'description' => [
            'SR Enterprises presents a housing project located in Pathauli Village, Pathauli Village. The project comes equipped with all the basic facilities necessary to meet daily requirements of the modern urban lifestyle of its residents, including .',
            'In S R Landmark City, the interiors are thoughtfully designed to provide adequate space, light and ventilation to the residential units. Pathauli Village is well-connected to other parts of the city via an extensive road.',
        ],
        'location' => 'Residential Growth Zone, Agra',
        'price' => 'On request',
        'priceSuffix' => '',
        'beds' => '3',
        'baths' => '2',
        'sqft' => '1180',
        'overviewId' => 'LC-118',
        'nearby' => 'Near schools, local shops, and main access roads that support day-to-day convenience.',
        'nearbyItems' => [
            'Within 10.5 km of Jaipur Highway',
            'Well Connected by Shastripuram Area',
            'Nearby Schools, Hospitals, Markets',
            'Eco-friendly Lifestyle with Veteran Trees',
        ],
        // 'overview' => [
        //     ['icon' => 'icon-house-line', 'label' => 'ID', 'value' => 'LC-118'],
        //     ['icon' => 'icon-sliders-horizontal', 'label' => 'Type', 'value' => 'Plot'],
        //     ['icon' => 'icon-garage', 'label' => 'Garages', 'value' => '1'],
        //     ['icon' => 'icon-bed1', 'label' => 'Bedrooms', 'value' => '3 Rooms'],
        //     ['icon' => 'icon-bathtub', 'label' => 'Bathrooms', 'value' => '2 Rooms'],
        //     ['icon' => 'icon-crop', 'label' => 'Land Size', 'value' => '1180 SqFt'],
        //     ['icon' => 'icon-hammer', 'label' => 'Year Built', 'value' => '2024'],
        //     ['icon' => 'icon-ruler', 'label' => 'Size', 'value' => '1180 SqFt'],
        // ],
        'details' => [
            ['label' => 'ID', 'value' => '#LC-118'],
            // ['label' => 'Beds', 'value' => '3'],
            ['label' => 'Price', 'value' => 'On request'],
            ['label' => 'Year built', 'value' => 'Aug 2017'],
            ['label' => 'Size', 'value' => '925 - 1350 sq.ft'],
            ['label' => 'Type', 'value' => '3 BHK Apartment'],
            // ['label' => 'Rooms', 'value' => '9'],
            ['label' => 'Status', 'value' => 'For sale'],
            // ['label' => 'Baths', 'value' => '2'],
            // ['label' => 'Garage', 'value' => '1'],
        ],
        // 'attachments' => [
        //     ['image' => 'images/home/file-1.png', 'name' => 'Landmark-City-Brochure.pdf'],
        //     ['image' => 'images/home/file-2.png', 'name' => 'Landmark-City-Price-List.pdf'],
        // ],
        'features' => [
            ['Gymnasium', 'Visitor Parking', 'Badminton Court'],
            ['Temple', 'Childrens Play Area', 'Transport routes'],
            ['Jogging Track', '24x7 CCTV Surveillance', 'Street Lighting'],
        ],
        'map' => [
            'address' => 'Patholi, Agra',
            'city' => 'Agra',
            'state' => 'Uttar Pradesh',
            'postal' => '282001',
            'area' => '925 - 1350 sq.ft',
            'country' => 'India',
        ],

        'mapEmbed' => 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d4210.519845506866!2d77.930008!3d27.1690924!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x397477d50dda2379%3A0xfeb98ef1376cf830!2sLandmark%20City!5e1!3m2!1sen!2sin!4v1775708198339!5m2!1sen!2sin',
        'websiteUrl' => 'https://housing.com/in/buy/projects/page/234112-landmark-city-by-rainbow-infra-housing-pvt-ltd-in-pathauli-village',
        'websiteLabel' => 'Click here for more details',
    ],
    'dream-avenue' => [
        'name' => 'Dream Avenues',
        'slug' => 'dream-avenue',
        'pageTitle' => 'Dream Avenues - BM Real Estate',
        'category' => 'Plot',
        'detailPage' => 'property-details/dream-avenue.php',
        'heroImage' => 'images/featured-properties/dream-avenue.jpg',
        'galleryImages' => [
            'images/featured-properties/dream-avenue.jpg',
            'images/all-properties/dream-avenues.webp',
            'images/all-properties/dream-avenues2.webp',
            'images/all-properties/dream-avenues3.webp',
        ],
        'summary' => 'An emerging residential destination with peaceful surroundings and attractive investment scope.',
        'description' => [
            'Dream avenues offers commercial spaces in its residential development located on nh-19, near the yamuna expressway and approximately 15 minutes from agra.',
            'These commercial opportunities are situated in a gated society, ideal for businesses seeking a prime location with high visibility and accessibility.',
        ],
        'location' => 'Main Residential Road, Agra',
        'price' => 'On request',
        'priceSuffix' => '',
        'beds' => '3',
        'baths' => '2',
        'sqft' => '1250',
        'overviewId' => 'DA-126',
        'nearby' => 'Conveniently placed near neighborhood retail, transport access, and emerging residential demand.',
        'nearbyItems' => [
            'just 5 minutes away from the yamuna expressway',
            '15 minutes away from the heart of agra',
            'Situated directly on nh-19',
            'Essential services and convenience facilities within reach.',
        ],
        // 'overview' => [
        //     ['icon' => 'icon-house-line', 'label' => 'ID', 'value' => 'DA-126'],
        //     ['icon' => 'icon-sliders-horizontal', 'label' => 'Type', 'value' => 'Plot'],
        //     ['icon' => 'icon-garage', 'label' => 'Garages', 'value' => '1'],
        //     ['icon' => 'icon-bed1', 'label' => 'Bedrooms', 'value' => '3 Rooms'],
        //     ['icon' => 'icon-bathtub', 'label' => 'Bathrooms', 'value' => '2 Rooms'],
        //     ['icon' => 'icon-crop', 'label' => 'Land Size', 'value' => '1250 SqFt'],
        //     ['icon' => 'icon-hammer', 'label' => 'Year Built', 'value' => '2024'],
        //     ['icon' => 'icon-ruler', 'label' => 'Size', 'value' => '1250 SqFt'],
        // ],
        'details' => [
            ['label' => 'ID', 'value' => '#DA-126'],
            // ['label' => 'Beds', 'value' => '3'],
            ['label' => 'Price', 'value' => 'On request'],
            ['label' => 'Year built', 'value' => 'July 15, 2029'],
            ['label' => 'Size', 'value' => '1800 sqft'],
            ['label' => 'Type', 'value' => 'Plot'],
            // ['label' => 'Rooms', 'value' => '9'],
            ['label' => 'Status', 'value' => 'For sale'],
            // ['label' => 'Baths', 'value' => '2'],
            // ['label' => 'Garage', 'value' => '1'],
        ],
        // 'attachments' => [
        //     ['image' => 'images/home/file-1.png', 'name' => 'Dream-Avenue-Brochure.pdf'],
        //     ['image' => 'images/home/file-2.png', 'name' => 'Dream-Avenue-Price-List.pdf'],
        // ],
        'features' => [
            ['Corner Property', 'Overlooking Park', '24x7 Security', 'Temple'],
            ['Neighborhood retail nearby', 'Rain Water Harvesting', 'Overlooking Main Road', 'Family-oriented location', 'Secure project setting'],
            ['Water and power access', 'Green open space', 'Long-term appreciation', 'Community development', 'Balanced lifestyle potential'],
        ],
        'map' => [
            'address' => 'Firozabad Road near K.P. Engineering College, Agra',
            'city' => 'Agra',
            'state' => 'Uttar Pradesh',
            'postal' => '282005',
            'area' => '1800 SqFt',
            'country' => 'India',
        ],
        'mapEmbed' => 'https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d538645.2600611125!2d78.1759644!3d27.2314314!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x39746f002cf2088d%3A0xab82b045f8ec3021!2sDream%20Avenues!5e1!3m2!1sen!2sin!4v1775710022933!5m2!1sen!2sin',
        'websiteUrl' => '#',
        'websiteLabel' => 'Click here for more details',
    ],
    'emporium-block' => [
        'name' => 'Emporium Block',
        'slug' => 'emporium-block',
        'pageTitle' => 'Emporium Block - BM Real Estate',
        'category' => 'Office',
        'detailPage' => 'property-details/emporium-block.php',
        'heroImage' => 'images/featured-properties/corporate-park.png',
        'galleryImages' => [
            'images/banner/banner-property-1.jpg',
            'images/banner/banner-property-2.jpg',
            'images/banner/banner-property-3.jpg',
            // 'images/featured-properties/dream-avenue.jpg',
        ],
        'summary' => 'A commercial block planned for premium retail and business spaces in a well-connected area.',
        'description' => [
            'Emporium Block is an upcoming commercial project under construction, designed to support retail and office use in a compact, practical format.',
            'The project is positioned for business buyers who want a clean layout, strong visibility, and future commercial demand.',
        ],
        'location' => 'Central Commercial District, Agra',
        'price' => 'On request',
        'priceSuffix' => '',
        'beds' => '2',
        'baths' => '2',
        'sqft' => '900',
        'overviewId' => 'EB-420',
        'nearby' => 'Close to retail movement, service businesses, and commercial road traffic.',
        'nearbyItems' => [
            'Multiple offices, banks, coaching centers',
            'Co-working spaces and IT companies',
            'Government offices and service centers',
            // 'Customer access and transport convenience for offices.',
        ],
        // 'overview' => [
        //     ['icon' => 'icon-house-line', 'label' => 'ID', 'value' => 'EB-420'],
        //     ['icon' => 'icon-sliders-horizontal', 'label' => 'Type', 'value' => 'Office'],
        //     ['icon' => 'icon-garage', 'label' => 'Garages', 'value' => '1'],
        //     ['icon' => 'icon-bed1', 'label' => 'Bedrooms', 'value' => '2 Rooms'],
        //     ['icon' => 'icon-bathtub', 'label' => 'Bathrooms', 'value' => '2 Rooms'],
        //     ['icon' => 'icon-crop', 'label' => 'Land Size', 'value' => '900 SqFt'],
        //     ['icon' => 'icon-hammer', 'label' => 'Year Built', 'value' => '2024'],
        //     ['icon' => 'icon-ruler', 'label' => 'Size', 'value' => '900 SqFt'],
        // ],
        'details' => [
            ['label' => 'ID', 'value' => '#EB-420'],
            // ['label' => 'Beds', 'value' => '2'],
            ['label' => 'Price', 'value' => 'On request'],
            ['label' => 'Year built', 'value' => '2024'],
            ['label' => 'Size', 'value' => '900 sqft'],
            ['label' => 'Type', 'value' => 'Office'],
            // ['label' => 'Rooms', 'value' => '7'],
            ['label' => 'Status', 'value' => 'For sale'],
            // ['label' => 'Baths', 'value' => '2'],
            // ['label' => 'Garage', 'value' => '1'],
        ],
        // 'attachments' => [
        //     ['image' => 'images/home/file-1.png', 'name' => 'Emporium-Block-Brochure.pdf'],
        //     ['image' => 'images/home/file-2.png', 'name' => 'Emporium-Block-Price-List.pdf'],
        // ],
        'features' => [
            ['24x7 Security', 'Car Parking', 'Lifts'],
            ['24/7 Water Supply', '24/7 Power Backup', 'Grade A Building'],
            ['Business support nearby', 'Service routes close by', 'Delivery access'],
        ],
        'map' => [
            'address' => 'Emporium Block, Sanjay Place, Agra',
            'city' => 'Agra',
            'state' => 'Uttar Pradesh',
            'postal' => '282002',
            'area' => '900 SqFt',
            'country' => 'India',
        ],
        'mapEmbed' => 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d4209.415097158735!2d78.00157787597884!3d27.198368047755366!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x39747747173e7289%3A0xcc0eebb90e9a8158!2semporium%20block%2C%20Sanjay%20Palace%2C%20Sanjay%20Place%2C%20Civil%20Lines%2C%20Agra%2C%20Uttar%20Pradesh%20282002!5e1!3m2!1sen!2sin!4v1775710816270!5m2!1sen!2sin',
        'websiteUrl' => '#',
        'websiteLabel' => 'Click here for more details',
    ],
    'corporate-park-agra' => [
        'name' => 'Corporate Park Agra',
        'slug' => 'corporate-park-agra',
        'pageTitle' => 'Corporate Park Agra - BM Real Estate',
        'category' => 'Office',
        'detailPage' => 'property-details/corporate-park-agra.php',
        'heroImage' => 'images/featured-properties/corporate-park.png',
        'galleryImages' => [
            'images/featured-properties/corporate-park.png',
            'images/banner/banner-property-1.jpg',
            'images/banner/banner-property-3.jpg',
            // 'images/featured-properties/green-valley-empire.jpg',
        ],
        'summary' => 'A modern commercial project planned for business needs, investment demand, and visibility.',
        'description' => [
            'Looking for property investment opportunities in Agra, Agra Infraland Corporate park can be the right bet for you.It is a ready to move project in Sanjay Place , Agra, offering investment options within your budget.',
            ' For those looking for exciting returns on investment, Agra Infraland Corporate park is Agra most desirable commercial project, where property options are available in varied budget range. ',
        ],
        'location' => 'Agra Business Corridor',
        'price' => 'On request',
        'priceSuffix' => '',
        'beds' => '2',
        'baths' => '2',
        'sqft' => '1050',
        'overviewId' => 'CPA-502',
        'nearby' => 'Located near active commercial movement, service routes, and business-friendly infrastructure.',
        'nearbyItems' => [
            'Multiple offices, banks, coaching centers',
            'Co-working spaces and IT companies',
            'Government offices and service centers',
            // 'Customer access and transport convenience for offices.',
        ],
        'overview' => [
            ['icon' => 'icon-house-line', 'label' => 'ID', 'value' => 'CPA-502'],
            ['icon' => 'icon-sliders-horizontal', 'label' => 'Type', 'value' => 'Office'],
            ['icon' => 'icon-garage', 'label' => 'Garages', 'value' => '1'],
            ['icon' => 'icon-bed1', 'label' => 'Bedrooms', 'value' => '2 Rooms'],
            ['icon' => 'icon-bathtub', 'label' => 'Bathrooms', 'value' => '2 Rooms'],
            ['icon' => 'icon-crop', 'label' => 'Land Size', 'value' => '1050 SqFt'],
            ['icon' => 'icon-hammer', 'label' => 'Year Built', 'value' => '2024'],
            ['icon' => 'icon-ruler', 'label' => 'Size', 'value' => '1050 SqFt'],
        ],
        'details' => [
            ['label' => 'ID', 'value' => '#CPA-502'],
            // ['label' => 'Beds', 'value' => '2'],
            ['label' => 'Price', 'value' => 'On request'],
            ['label' => 'Year built', 'value' => 'Jun, 2018'],
            ['label' => 'Size', 'value' => '1050 sqft'],
            ['label' => 'Type', 'value' => 'Office'],
            // ['label' => 'Rooms', 'value' => '8'],
            ['label' => 'Status', 'value' => 'For Rent'],
            // ['label' => 'Baths', 'value' => '2'],
            // ['label' => 'Garage', 'value' => '1'],
        ],
        // 'attachments' => [
        //     ['image' => 'images/home/file-1.png', 'name' => 'Corporate-Park-Brochure.pdf'],
        //     ['image' => 'images/home/file-2.png', 'name' => 'Corporate-Park-Price-List.pdf'],
        // ],
        'features' => [
            ['24x7 Security', 'Car Parking', 'Lifts'],
            ['24/7 Water Supply', '24/7 Power Backup', 'Grade A Building'],
            ['Business support nearby', 'Service routes close by', 'Delivery access'],
        ],
        'map' => [
            'address' => 'Sanjay Palace, Sanjay Place, Civil Lines, Agra',
            'city' => 'Agra',
            'state' => 'Uttar Pradesh',
            'postal' => '282002',
            'area' => '1050 SqFt',
            'country' => 'India',
        ],
        'mapEmbed' => 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d4209.352020133202!2d78.0082523!3d27.2000387!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x397477ad7106acf1%3A0xa6379bee5878de32!2sCorporate%20Park%2C%20Sanjay%20Place%2C%20Agra!5e1!3m2!1sen!2sin!4v1775710573058!5m2!1sen!2sin',
        'websiteUrl' => '#',
        'websiteLabel' => 'Click here for more details',
    ],
    'padamdeep-tower' => [
        'name' => 'Padamdeep Tower',
        'slug' => 'padamdeep-tower',
        'pageTitle' => 'Padamdeep Tower - BM Real Estate',
        'category' => 'Office',
        'detailPage' => 'property-details/padamdeep-tower.php',
        'heroImage' => 'images/featured-properties/padamdeep-tower.png',
        'galleryImages' => [
            'images/featured-properties/padamdeep-tower.png',
            'images/banner/banner-property-1.jpg',
            'images/banner/banner-property-2.jpg',
            // 'images/featured-properties/Vrindavan-scaled.jpg',
        ],
        'summary' => 'A commercial tower concept designed for modern business spaces in a prime location.',
        'description' => [
            "Situated in Sanjay Place, the Padamdeep Tower is planned to offer a modern lifestyle to all the residents. Padamdeep Tower is a high-quality yet affordable residential project by Shree Riddhi Siddhi Real Ventures LLP. The site's complete address is Sanjay Place, Madhu Nagar, Agra, Uttar Pradesh.",
            ' Its pincode is 282002. With all modern conveniences at your disposal, Padamdeep Tower will ensure a quality living experience.',
        ],
        'location' => 'Prime Commercial Zone, Agra',
        'price' => 'On request',
        'priceSuffix' => '',
        'beds' => '2',
        'baths' => '2',
        'sqft' => '980',
        'overviewId' => 'PT-618',
        'nearby' => 'Near business activity, roadway access, and commercial support services.',
        'nearbyItems' => [
            'Multiple offices, banks, coaching centers',
            'Co-working spaces and IT companies',
            'Government offices and service centers',
            // 'Customer access and transport convenience for offices.',
        ],
        // 'overview' => [
        //     ['icon' => 'icon-house-line', 'label' => 'ID', 'value' => 'PT-618'],
        //     ['icon' => 'icon-sliders-horizontal', 'label' => 'Type', 'value' => 'Office'],
        //     ['icon' => 'icon-garage', 'label' => 'Garages', 'value' => '1'],
        //     ['icon' => 'icon-bed1', 'label' => 'Bedrooms', 'value' => '2 Rooms'],
        //     ['icon' => 'icon-bathtub', 'label' => 'Bathrooms', 'value' => '2 Rooms'],
        //     ['icon' => 'icon-crop', 'label' => 'Land Size', 'value' => '980 SqFt'],
        //     ['icon' => 'icon-hammer', 'label' => 'Year Built', 'value' => '2024'],
        //     ['icon' => 'icon-ruler', 'label' => 'Size', 'value' => '980 SqFt'],
        // ],
        'details' => [
            ['label' => 'ID', 'value' => '#PT-618'],
            // ['label' => 'Beds', 'value' => '2'],
            ['label' => 'Price', 'value' => 'On request'],
            ['label' => 'Year built', 'value' => '2024'],
            ['label' => 'Size', 'value' => '980 sqft'],
            ['label' => 'Type', 'value' => 'Office/flats'],
            // ['label' => 'Rooms', 'value' => '8'],
            ['label' => 'Status', 'value' => 'For sale'],
            // ['label' => 'Baths', 'value' => '2'],
            // ['label' => 'Garage', 'value' => '1'],
        ],
        // 'attachments' => [
        //     ['image' => 'images/home/file-1.png', 'name' => 'Padamdeep-Tower-Brochure.pdf'],
        //     ['image' => 'images/home/file-2.png', 'name' => 'Padamdeep-Tower-Price-List.pdf'],
        // ],
        'features' => [
            ['24/7 Power Backup', 'Car Parking', 'Lifts'],
            ['24/7 Water Supply', '24x7 Security', 'Grade A Building'],
            ['Business support nearby', 'Service routes close by', 'Delivery access'],
        ],
        'map' => [
            'address' => 'Wazirpura Rd, Sanjay Palace, Sanjay Place, Agra',
            'city' => 'Agra',
            'state' => 'Uttar Pradesh',
            'postal' => '282002',
            'area' => '980 SqFt',
            'country' => 'India',
        ],

        
        'mapEmbed' => 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d4209.442459569624!2d78.00629359999999!3d27.1976433!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3974774796a70893%3A0x1d4eeb3bded1673!2sPadamdeep%20Tower%2C%20Wazirpura%20Rd%2C%20Sanjay%20Palace%2C%20Sanjay%20Place%2C%20Madhu%20Nagar%2C%20Agra%2C%20Uttar%20Pradesh%20282002!5e1!3m2!1sen!2sin!4v1775711517642!5m2!1sen!2sin',
        'websiteUrl' => '#',
        'websiteLabel' => 'Click here for more details',
    ],
];
