<?php

return [
    'grand-valley-empire' => [
        'name' => 'Grand Valley Empire',
        'slug' => 'grand-valley-empire',
        'pageTitle' => 'Grand Valley Empire - BM Real Estate',
        'category' => 'Plot',
        'detailPage' => 'property-details/grand-valley-empire.php',
        'heroImage' => 'images/featured-properties/grand-green-valley.jpg',
        'galleryImages' => [
            'images/featured-properties/grand-green-valley.jpg',
            'images/banner/banner-property-1.jpg',
            'images/banner/banner-property-2.jpg',
            'images/banner/banner-property-3.jpg',
        ],
        'summary' => 'A premium plotted township with modern planning, wide roads, and steady investment potential.',
        'description' => [
            'Grand Valley Empire is a promising residential project currently under construction on the Etmadpur to Behran Road in Agra.',
            'The layout is designed for practical living with clear plotting, open surroundings, and long-term value for buyers and investors.',
        ],
        'location' => 'Etmadpur to Behran Road, Agra',
        'price' => 'On request',
        'priceSuffix' => '',
        'beds' => '3',
        'baths' => '2',
        'sqft' => '1150',
        'overviewId' => 'GVE-101',
        'nearby' => 'Located close to developing residential neighborhoods, main road access, and essential daily conveniences.',
        'overview' => [
            ['icon' => 'icon-house-line', 'label' => 'ID', 'value' => 'GVE-101'],
            ['icon' => 'icon-sliders-horizontal', 'label' => 'Type', 'value' => 'Plot'],
            ['icon' => 'icon-garage', 'label' => 'Garages', 'value' => '1'],
            ['icon' => 'icon-bed1', 'label' => 'Bedrooms', 'value' => '3 Rooms'],
            ['icon' => 'icon-bathtub', 'label' => 'Bathrooms', 'value' => '2 Rooms'],
            ['icon' => 'icon-crop', 'label' => 'Land Size', 'value' => '1150 SqFt'],
            ['icon' => 'icon-hammer', 'label' => 'Year Built', 'value' => '2024'],
            ['icon' => 'icon-ruler', 'label' => 'Size', 'value' => '1150 SqFt'],
        ],
        'details' => [
            ['label' => 'ID', 'value' => '#GVE-101'],
            ['label' => 'Beds', 'value' => '3'],
            ['label' => 'Price', 'value' => '250000'],
            ['label' => 'Year built', 'value' => '2024'],
            ['label' => 'Size', 'value' => '1150 sqft'],
            ['label' => 'Type', 'value' => 'Plot'],
            ['label' => 'Rooms', 'value' => '9'],
            ['label' => 'Status', 'value' => 'For sale'],
            ['label' => 'Baths', 'value' => '2'],
            ['label' => 'Garage', 'value' => '1'],
        ],
        // 'attachments' => [
        //     ['image' => 'images/home/file-1.png', 'name' => 'Grand-Valley-Empire-Brochure.pdf'],
        //     ['image' => 'images/home/file-2.png', 'name' => 'Grand-Valley-Empire-Price-List.pdf'],
        // ],
        'features' => [
            ['Wide internal roads', 'Corner plot options', 'Open green surroundings', 'Boundary planning', 'Easy access routes'],
            ['Water and electricity provisions', 'Family-friendly layout', 'Investment-ready location', 'Future appreciation potential', 'Peaceful neighborhood feel'],
            ['Nearby schools', 'Nearby retail access', 'Public transport access', 'Low-density planning', 'Secure township feel'],
        ],
        'map' => [
            'address' => 'Etmadpur to Behran Road, Agra',
            'city' => 'Agra',
            'state' => 'Uttar Pradesh',
            'postal' => '283202',
            'area' => '1150 SqFt',
            'country' => 'India',
        ],
        'mapEmbed' => 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3555.3345643201914!2d78.15436161504066!3d27.193423982979306!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3974f4ed8a8b8e3b%3A0x0!2sAgra%2C%20Uttar%20Pradesh!5e0!3m2!1sen!2sin!4v1710000000000!5m2!1sen!2sin',
    ],
    'vrindavan-global' => [
        'name' => 'Vrindavan Global',
        'slug' => 'vrindavan-global',
        'pageTitle' => 'Vrindavan Global - BM Real Estate',
        'category' => 'Farmhouse',
        'detailPage' => 'property-details/vrindavan-global.php',
        'heroImage' => 'images/featured-properties/vrindavan-global.jpg',
        'galleryImages' => [
            'images/featured-properties/vrindavan-global.jpg',
            'images/featured-properties/Vrindavan-scaled.jpg',
            'images/banner/banner-property-2.jpg',
            'images/banner/banner-property-3.jpg',
        ],
        'summary' => 'A large township concept inspired by spiritual harmony and modern family living.',
        'description' => [
            'Vrindavan Global is an ambitious residential township designed to offer a peaceful environment with modern infrastructure.',
            'Its open planning, green-focused surroundings, and strong connectivity make it suitable for buyers seeking a balanced lifestyle.',
        ],
        'location' => 'Vrindavan, Mathura',
        'price' => 'On request',
        'priceSuffix' => '',
        'beds' => '3',
        'baths' => '2',
        'sqft' => '1400',
        'overviewId' => 'VG-204',
        'nearby' => 'Set near temple corridors, local markets, and future-ready access roads for easy movement.',
        'overview' => [
            ['icon' => 'icon-house-line', 'label' => 'ID', 'value' => 'VG-204'],
            ['icon' => 'icon-sliders-horizontal', 'label' => 'Type', 'value' => 'Farmhouse'],
            ['icon' => 'icon-garage', 'label' => 'Garages', 'value' => '1'],
            ['icon' => 'icon-bed1', 'label' => 'Bedrooms', 'value' => '3 Rooms'],
            ['icon' => 'icon-bathtub', 'label' => 'Bathrooms', 'value' => '2 Rooms'],
            ['icon' => 'icon-crop', 'label' => 'Land Size', 'value' => '1400 SqFt'],
            ['icon' => 'icon-hammer', 'label' => 'Year Built', 'value' => '2024'],
            ['icon' => 'icon-ruler', 'label' => 'Size', 'value' => '1400 SqFt'],
        ],
        'details' => [
            ['label' => 'ID', 'value' => '#VG-204'],
            ['label' => 'Beds', 'value' => '3'],
            ['label' => 'Price', 'value' => 'On request'],
            ['label' => 'Year built', 'value' => '2024'],
            ['label' => 'Size', 'value' => '1400 sqft'],
            ['label' => 'Type', 'value' => 'Farmhouse'],
            ['label' => 'Rooms', 'value' => '9'],
            ['label' => 'Status', 'value' => 'For sale'],
            ['label' => 'Baths', 'value' => '2'],
            ['label' => 'Garage', 'value' => '1'],
        ],
        // 'attachments' => [
        //     ['image' => 'images/home/file-1.png', 'name' => 'Vrindavan-Global-Brochure.pdf'],
        //     ['image' => 'images/home/file-2.png', 'name' => 'Vrindavan-Global-Price-List.pdf'],
        // ],
        'features' => [
            ['Spacious green surroundings', 'Spiritual neighborhood setting', 'Open plots', 'Gated township planning', 'Peaceful approach roads'],
            ['Modern infrastructure', 'Family living focus', 'Good connectivity', 'Investment potential', 'Natural ambience'],
            ['Temple corridor access', 'Local markets nearby', 'School access', 'Transport connectivity', 'Community-friendly layout'],
        ],
        'map' => [
            'address' => 'Vrindavan, Mathura',
            'city' => 'Mathura',
            'state' => 'Uttar Pradesh',
            'postal' => '281121',
            'area' => '1400 SqFt',
            'country' => 'India',
        ],
        'mapEmbed' => 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3559.757380260725!2d77.67002611503731!3d27.56510288284678!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3973950b6c2ec1d5%3A0x0!2sVrindavan%2C%20Uttar%20Pradesh!5e0!3m2!1sen!2sin!4v1710000000001!5m2!1sen!2sin',
    ],
    'green-valley-empire' => [
        'name' => 'Green Valley Empire',
        'slug' => 'green-valley-empire',
        'pageTitle' => 'Green Valley Empire - BM Real Estate',
        'category' => 'Farmhouse',
        'detailPage' => 'property-details/green-valley-empire.php',
        'heroImage' => 'images/featured-properties/green-valley-empire.jpg',
        'galleryImages' => [
            'images/featured-properties/green-valley-empire.jpg',
            'images/banner/banner-property-1.jpg',
            'images/banner/banner-property-2.jpg',
            'images/banner/banner-property-3.jpg',
        ],
        'summary' => 'A thoughtfully designed community project with comfort, accessibility, and long-term value.',
        'description' => [
            'Green Valley Empire is a residential project under construction with a layout focused on everyday convenience and a calm neighborhood feel.',
            'The project blends organized development with a location that supports future residential growth and investment confidence.',
        ],
        'location' => 'Agra Road Corridor',
        'price' => 'On request',
        'priceSuffix' => '',
        'beds' => '3',
        'baths' => '2',
        'sqft' => '1325',
        'overviewId' => 'GVE-214',
        'nearby' => 'Conveniently positioned near schools, transport links, and everyday retail needs.',
        'overview' => [
            ['icon' => 'icon-house-line', 'label' => 'ID', 'value' => 'GVE-214'],
            ['icon' => 'icon-sliders-horizontal', 'label' => 'Type', 'value' => 'Farmhouse'],
            ['icon' => 'icon-garage', 'label' => 'Garages', 'value' => '1'],
            ['icon' => 'icon-bed1', 'label' => 'Bedrooms', 'value' => '3 Rooms'],
            ['icon' => 'icon-bathtub', 'label' => 'Bathrooms', 'value' => '2 Rooms'],
            ['icon' => 'icon-crop', 'label' => 'Land Size', 'value' => '1325 SqFt'],
            ['icon' => 'icon-hammer', 'label' => 'Year Built', 'value' => '2024'],
            ['icon' => 'icon-ruler', 'label' => 'Size', 'value' => '1325 SqFt'],
        ],
        'details' => [
            ['label' => 'ID', 'value' => '#GVE-214'],
            ['label' => 'Beds', 'value' => '3'],
            ['label' => 'Price', 'value' => 'On request'],
            ['label' => 'Year built', 'value' => '2024'],
            ['label' => 'Size', 'value' => '1325 sqft'],
            ['label' => 'Type', 'value' => 'Farmhouse'],
            ['label' => 'Rooms', 'value' => '9'],
            ['label' => 'Status', 'value' => 'For sale'],
            ['label' => 'Baths', 'value' => '2'],
            ['label' => 'Garage', 'value' => '1'],
        ],
        // 'attachments' => [
        //     ['image' => 'images/home/file-1.png', 'name' => 'Green-Valley-Empire-Brochure.pdf'],
        //     ['image' => 'images/home/file-2.png', 'name' => 'Green-Valley-Empire-Price-List.pdf'],
        // ],
        'features' => [
            ['Landscaped common areas', 'Wide planning streets', 'Community access points', 'Open frontage', 'Secure township setup'],
            ['Family-oriented layout', 'Long-term growth area', 'Convenient daily access', 'Clear boundary marking', 'Investment-friendly zone'],
            ['Schools nearby', 'Medical support nearby', 'Retail convenience', 'Transport access', 'Peaceful surroundings'],
        ],
        'map' => [
            'address' => 'Agra Road Corridor',
            'city' => 'Agra',
            'state' => 'Uttar Pradesh',
            'postal' => '282001',
            'area' => '1325 SqFt',
            'country' => 'India',
        ],
        'mapEmbed' => 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3556.9579156942015!2d78.04414161503943!3d27.210193882974807!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3974f0c97d3db1b3%3A0x0!2sAgra%2C%20Uttar%20Pradesh!5e0!3m2!1sen!2sin!4v1710000000002!5m2!1sen!2sin',
    ],
    'upsic-project' => [
        'name' => 'The UPSIC Project',
        'slug' => 'upsic-project',
        'pageTitle' => 'The UPSIC Project - BM Real Estate',
        'category' => 'Farmhouse',
        'detailPage' => 'property-details/upsic-project.php',
        'heroImage' => 'images/featured-properties/upsic.jpg',
        'galleryImages' => [
            'images/featured-properties/upsic.jpg',
            'images/banner/banner-property-1.jpg',
            'images/banner/banner-property-2.jpg',
            'images/banner/banner-property-3.jpg',
        ],
        'summary' => 'A planned project built for secure investment with organized infrastructure and growth potential.',
        'description' => [
            'The UPSIC Project is an upcoming development planned to deliver structured plots and practical infrastructure in a strategic location.',
            'It is positioned for buyers looking for future-ready land with a straightforward development layout and strong accessibility.',
        ],
        'location' => 'Strategic Growth Zone, Agra',
        'price' => 'On request',
        'priceSuffix' => '',
        'beds' => '3',
        'baths' => '2',
        'sqft' => '1600',
        'overviewId' => 'UP-310',
        'nearby' => 'Close to developing civic infrastructure, road connections, and planned neighborhood services.',
        'overview' => [
            ['icon' => 'icon-house-line', 'label' => 'ID', 'value' => 'UP-310'],
            ['icon' => 'icon-sliders-horizontal', 'label' => 'Type', 'value' => 'Farmhouse'],
            ['icon' => 'icon-garage', 'label' => 'Garages', 'value' => '1'],
            ['icon' => 'icon-bed1', 'label' => 'Bedrooms', 'value' => '3 Rooms'],
            ['icon' => 'icon-bathtub', 'label' => 'Bathrooms', 'value' => '2 Rooms'],
            ['icon' => 'icon-crop', 'label' => 'Land Size', 'value' => '1600 SqFt'],
            ['icon' => 'icon-hammer', 'label' => 'Year Built', 'value' => '2024'],
            ['icon' => 'icon-ruler', 'label' => 'Size', 'value' => '1600 SqFt'],
        ],
        'details' => [
            ['label' => 'ID', 'value' => '#UP-310'],
            ['label' => 'Beds', 'value' => '3'],
            ['label' => 'Price', 'value' => 'On request'],
            ['label' => 'Year built', 'value' => '2024'],
            ['label' => 'Size', 'value' => '1600 sqft'],
            ['label' => 'Type', 'value' => 'Farmhouse'],
            ['label' => 'Rooms', 'value' => '9'],
            ['label' => 'Status', 'value' => 'For sale'],
            ['label' => 'Baths', 'value' => '2'],
            ['label' => 'Garage', 'value' => '1'],
        ],
        // 'attachments' => [
        //     ['image' => 'images/home/file-1.png', 'name' => 'UPSIC-Project-Brochure.pdf'],
        //     ['image' => 'images/home/file-2.png', 'name' => 'UPSIC-Project-Price-List.pdf'],
        // ],
        'features' => [
            ['Structured plot layout', 'Wide service access', 'Future-ready infrastructure', 'High connectivity potential', 'Reliable growth corridor'],
            ['Investment-focused project', 'Good road access', 'Planned utilities', 'Secure development layout', 'Long-term asset value'],
            ['Nearby civic development', 'Retail support close by', 'Schools and services nearby', 'Low maintenance needs', 'Accessible location'],
        ],
        'map' => [
            'address' => 'Strategic Growth Zone, Agra',
            'city' => 'Agra',
            'state' => 'Uttar Pradesh',
            'postal' => '282007',
            'area' => '1600 SqFt',
            'country' => 'India',
        ],
        'mapEmbed' => 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3556.9579156942015!2d78.04414161503943!3d27.210193882974807!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3974f0c97d3db1b3%3A0x0!2sAgra%2C%20Uttar%20Pradesh!5e0!3m2!1sen!2sin!4v1710000000003!5m2!1sen!2sin',
    ],
    'landmark-city' => [
        'name' => 'The Landmark City',
        'slug' => 'landmark-city',
        'pageTitle' => 'The Landmark City - BM Real Estate',
        'category' => 'Plot',
        'detailPage' => 'property-details/landmark-city.php',
        'heroImage' => 'images/featured-properties/landmark-city.jpg',
        'galleryImages' => [
            'images/featured-properties/landmark-city.jpg',
            'images/banner/banner-property-1.jpg',
            'images/banner/banner-property-2.jpg',
            'images/banner/banner-property-3.jpg',
        ],
        'summary' => 'A modern plotted development with essential facilities and a family-friendly neighborhood concept.',
        'description' => [
            'The Landmark City is an emerging residential project designed with organized layouts, wide roads, and future-ready infrastructure.',
            'Its planning supports comfortable family living while also offering a strong base for long-term property appreciation.',
        ],
        'location' => 'Residential Growth Zone, Agra',
        'price' => 'On request',
        'priceSuffix' => '',
        'beds' => '3',
        'baths' => '2',
        'sqft' => '1180',
        'overviewId' => 'LC-118',
        'nearby' => 'Near schools, local shops, and main access roads that support day-to-day convenience.',
        'overview' => [
            ['icon' => 'icon-house-line', 'label' => 'ID', 'value' => 'LC-118'],
            ['icon' => 'icon-sliders-horizontal', 'label' => 'Type', 'value' => 'Plot'],
            ['icon' => 'icon-garage', 'label' => 'Garages', 'value' => '1'],
            ['icon' => 'icon-bed1', 'label' => 'Bedrooms', 'value' => '3 Rooms'],
            ['icon' => 'icon-bathtub', 'label' => 'Bathrooms', 'value' => '2 Rooms'],
            ['icon' => 'icon-crop', 'label' => 'Land Size', 'value' => '1180 SqFt'],
            ['icon' => 'icon-hammer', 'label' => 'Year Built', 'value' => '2024'],
            ['icon' => 'icon-ruler', 'label' => 'Size', 'value' => '1180 SqFt'],
        ],
        'details' => [
            ['label' => 'ID', 'value' => '#LC-118'],
            ['label' => 'Beds', 'value' => '3'],
            ['label' => 'Price', 'value' => 'On request'],
            ['label' => 'Year built', 'value' => '2024'],
            ['label' => 'Size', 'value' => '1180 sqft'],
            ['label' => 'Type', 'value' => 'Plot'],
            ['label' => 'Rooms', 'value' => '9'],
            ['label' => 'Status', 'value' => 'For sale'],
            ['label' => 'Baths', 'value' => '2'],
            ['label' => 'Garage', 'value' => '1'],
        ],
        // 'attachments' => [
        //     ['image' => 'images/home/file-1.png', 'name' => 'Landmark-City-Brochure.pdf'],
        //     ['image' => 'images/home/file-2.png', 'name' => 'Landmark-City-Price-List.pdf'],
        // ],
        'features' => [
            ['Wide plots', 'Organized access roads', 'Family-friendly planning', 'Future-ready services', 'Clean neighborhood layout'],
            ['Nearby retail access', 'School connectivity', 'Transport routes', 'Safe residential setting', 'Investment upside'],
            ['Main road access', 'Community utilities', 'Low-density planning', 'Open surroundings', 'Development potential'],
        ],
        'map' => [
            'address' => 'Residential Growth Zone, Agra',
            'city' => 'Agra',
            'state' => 'Uttar Pradesh',
            'postal' => '282006',
            'area' => '1180 SqFt',
            'country' => 'India',
        ],
        'mapEmbed' => 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3556.4578202754827!2d78.00994761503977!3d27.23552658296759!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3974711d7e5c4a77%3A0x0!2sAgra%2C%20Uttar%20Pradesh!5e0!3m2!1sen!2sin!4v1710000000004!5m2!1sen!2sin',
    ],
    'dream-avenue' => [
        'name' => 'Dream Avenue',
        'slug' => 'dream-avenue',
        'pageTitle' => 'Dream Avenue - BM Real Estate',
        'category' => 'Plot',
        'detailPage' => 'property-details/dream-avenue.php',
        'heroImage' => 'images/featured-properties/dream-avenue.jpg',
        'galleryImages' => [
            'images/featured-properties/dream-avenue.jpg',
            'images/banner/banner-property-1.jpg',
            'images/banner/banner-property-2.jpg',
            'images/banner/banner-property-3.jpg',
        ],
        'summary' => 'An emerging residential destination with peaceful surroundings and attractive investment scope.',
        'description' => [
            'Dream Avenue is a thoughtfully planned residential project currently under construction with a clear, modern layout.',
            'The project is positioned for buyers who want a calm living environment with practical access and growth potential.',
        ],
        'location' => 'Main Residential Road, Agra',
        'price' => 'On request',
        'priceSuffix' => '',
        'beds' => '3',
        'baths' => '2',
        'sqft' => '1250',
        'overviewId' => 'DA-126',
        'nearby' => 'Conveniently placed near neighborhood retail, transport access, and emerging residential demand.',
        'overview' => [
            ['icon' => 'icon-house-line', 'label' => 'ID', 'value' => 'DA-126'],
            ['icon' => 'icon-sliders-horizontal', 'label' => 'Type', 'value' => 'Plot'],
            ['icon' => 'icon-garage', 'label' => 'Garages', 'value' => '1'],
            ['icon' => 'icon-bed1', 'label' => 'Bedrooms', 'value' => '3 Rooms'],
            ['icon' => 'icon-bathtub', 'label' => 'Bathrooms', 'value' => '2 Rooms'],
            ['icon' => 'icon-crop', 'label' => 'Land Size', 'value' => '1250 SqFt'],
            ['icon' => 'icon-hammer', 'label' => 'Year Built', 'value' => '2024'],
            ['icon' => 'icon-ruler', 'label' => 'Size', 'value' => '1250 SqFt'],
        ],
        'details' => [
            ['label' => 'ID', 'value' => '#DA-126'],
            ['label' => 'Beds', 'value' => '3'],
            ['label' => 'Price', 'value' => 'On request'],
            ['label' => 'Year built', 'value' => '2024'],
            ['label' => 'Size', 'value' => '1250 sqft'],
            ['label' => 'Type', 'value' => 'Plot'],
            ['label' => 'Rooms', 'value' => '9'],
            ['label' => 'Status', 'value' => 'For sale'],
            ['label' => 'Baths', 'value' => '2'],
            ['label' => 'Garage', 'value' => '1'],
        ],
        // 'attachments' => [
        //     ['image' => 'images/home/file-1.png', 'name' => 'Dream-Avenue-Brochure.pdf'],
        //     ['image' => 'images/home/file-2.png', 'name' => 'Dream-Avenue-Price-List.pdf'],
        // ],
        'features' => [
            ['Modern residential planning', 'Peaceful layout', 'Easy access roads', 'Promising investment scope', 'Open surroundings'],
            ['Neighborhood retail nearby', 'Transport connectivity', 'Daily convenience access', 'Family-oriented location', 'Secure project setting'],
            ['Water and power access', 'Green open space', 'Long-term appreciation', 'Community development', 'Balanced lifestyle potential'],
        ],
        'map' => [
            'address' => 'Main Residential Road, Agra',
            'city' => 'Agra',
            'state' => 'Uttar Pradesh',
            'postal' => '282005',
            'area' => '1250 SqFt',
            'country' => 'India',
        ],
        'mapEmbed' => 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3556.128018129866!2d78.00722451504011!3d27.24837548296371!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x397471ab3f2d7d6b%3A0x0!2sAgra%2C%20Uttar%20Pradesh!5e0!3m2!1sen!2sin!4v1710000000005!5m2!1sen!2sin',
    ],
    'emporium-block' => [
        'name' => 'Emporium Block',
        'slug' => 'emporium-block',
        'pageTitle' => 'Emporium Block - BM Real Estate',
        'category' => 'Office',
        'detailPage' => 'property-details/emporium-block.php',
        'heroImage' => 'images/featured-properties/corporate-park.png',
        'galleryImages' => [
            'images/banner/banner-property-1.jpg',
            'images/banner/banner-property-2.jpg',
            'images/banner/banner-property-3.jpg',
            'images/featured-properties/dream-avenue.jpg',
        ],
        'summary' => 'A commercial block planned for premium retail and business spaces in a well-connected area.',
        'description' => [
            'Emporium Block is an upcoming commercial project under construction, designed to support retail and office use in a compact, practical format.',
            'The project is positioned for business buyers who want a clean layout, strong visibility, and future commercial demand.',
        ],
        'location' => 'Central Commercial District, Agra',
        'price' => 'On request',
        'priceSuffix' => '',
        'beds' => '2',
        'baths' => '2',
        'sqft' => '900',
        'overviewId' => 'EB-420',
        'nearby' => 'Close to retail movement, service businesses, and commercial road traffic.',
        'overview' => [
            ['icon' => 'icon-house-line', 'label' => 'ID', 'value' => 'EB-420'],
            ['icon' => 'icon-sliders-horizontal', 'label' => 'Type', 'value' => 'Office'],
            ['icon' => 'icon-garage', 'label' => 'Garages', 'value' => '1'],
            ['icon' => 'icon-bed1', 'label' => 'Bedrooms', 'value' => '2 Rooms'],
            ['icon' => 'icon-bathtub', 'label' => 'Bathrooms', 'value' => '2 Rooms'],
            ['icon' => 'icon-crop', 'label' => 'Land Size', 'value' => '900 SqFt'],
            ['icon' => 'icon-hammer', 'label' => 'Year Built', 'value' => '2024'],
            ['icon' => 'icon-ruler', 'label' => 'Size', 'value' => '900 SqFt'],
        ],
        'details' => [
            ['label' => 'ID', 'value' => '#EB-420'],
            ['label' => 'Beds', 'value' => '2'],
            ['label' => 'Price', 'value' => 'On request'],
            ['label' => 'Year built', 'value' => '2024'],
            ['label' => 'Size', 'value' => '900 sqft'],
            ['label' => 'Type', 'value' => 'Office'],
            ['label' => 'Rooms', 'value' => '7'],
            ['label' => 'Status', 'value' => 'For sale'],
            ['label' => 'Baths', 'value' => '2'],
            ['label' => 'Garage', 'value' => '1'],
        ],
        // 'attachments' => [
        //     ['image' => 'images/home/file-1.png', 'name' => 'Emporium-Block-Brochure.pdf'],
        //     ['image' => 'images/home/file-2.png', 'name' => 'Emporium-Block-Price-List.pdf'],
        // ],
        'features' => [
            ['Retail-ready frontage', 'Commercial visibility', 'Business-friendly layout', 'Easy customer access', 'Strategic market position'],
            ['Office and shop potential', 'Compact practical spaces', 'High footfall potential', 'Investment value', 'Modern commercial planning'],
            ['Main road exposure', 'Utilities access', 'Delivery-friendly access', 'Commercial ecosystem', 'Future business demand'],
        ],
        'map' => [
            'address' => 'Central Commercial District, Agra',
            'city' => 'Agra',
            'state' => 'Uttar Pradesh',
            'postal' => '282002',
            'area' => '900 SqFt',
            'country' => 'India',
        ],
        'mapEmbed' => 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3556.9579156942015!2d78.04414161503943!3d27.210193882974807!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3974f0c97d3db1b3%3A0x0!2sAgra%2C%20Uttar%20Pradesh!5e0!3m2!1sen!2sin!4v1710000000006!5m2!1sen!2sin',
    ],
    'corporate-park-agra' => [
        'name' => 'Corporate Park Agra',
        'slug' => 'corporate-park-agra',
        'pageTitle' => 'Corporate Park Agra - BM Real Estate',
        'category' => 'Office',
        'detailPage' => 'property-details/corporate-park-agra.php',
        'heroImage' => 'images/featured-properties/corporate-park.png',
        'galleryImages' => [
            'images/featured-properties/corporate-park.png',
            'images/banner/banner-property-1.jpg',
            'images/banner/banner-property-3.jpg',
            'images/featured-properties/green-valley-empire.jpg',
        ],
        'summary' => 'A modern commercial project planned for business needs, investment demand, and visibility.',
        'description' => [
            'Corporate Park Agra is a modern commercial project under construction, designed to meet growing business and investment requirements.',
            'Its layout emphasizes functional spaces, accessibility, and a professional environment for long-term use.',
        ],
        'location' => 'Agra Business Corridor',
        'price' => 'On request',
        'priceSuffix' => '',
        'beds' => '2',
        'baths' => '2',
        'sqft' => '1050',
        'overviewId' => 'CPA-502',
        'nearby' => 'Located near active commercial movement, service routes, and business-friendly infrastructure.',
        'overview' => [
            ['icon' => 'icon-house-line', 'label' => 'ID', 'value' => 'CPA-502'],
            ['icon' => 'icon-sliders-horizontal', 'label' => 'Type', 'value' => 'Office'],
            ['icon' => 'icon-garage', 'label' => 'Garages', 'value' => '1'],
            ['icon' => 'icon-bed1', 'label' => 'Bedrooms', 'value' => '2 Rooms'],
            ['icon' => 'icon-bathtub', 'label' => 'Bathrooms', 'value' => '2 Rooms'],
            ['icon' => 'icon-crop', 'label' => 'Land Size', 'value' => '1050 SqFt'],
            ['icon' => 'icon-hammer', 'label' => 'Year Built', 'value' => '2024'],
            ['icon' => 'icon-ruler', 'label' => 'Size', 'value' => '1050 SqFt'],
        ],
        'details' => [
            ['label' => 'ID', 'value' => '#CPA-502'],
            ['label' => 'Beds', 'value' => '2'],
            ['label' => 'Price', 'value' => 'On request'],
            ['label' => 'Year built', 'value' => '2024'],
            ['label' => 'Size', 'value' => '1050 sqft'],
            ['label' => 'Type', 'value' => 'Office'],
            ['label' => 'Rooms', 'value' => '8'],
            ['label' => 'Status', 'value' => 'For sale'],
            ['label' => 'Baths', 'value' => '2'],
            ['label' => 'Garage', 'value' => '1'],
        ],
        // 'attachments' => [
        //     ['image' => 'images/home/file-1.png', 'name' => 'Corporate-Park-Brochure.pdf'],
        //     ['image' => 'images/home/file-2.png', 'name' => 'Corporate-Park-Price-List.pdf'],
        // ],
        'features' => [
            ['Commercial tower concept', 'Prime business access', 'High visibility frontage', 'Modern office potential', 'Strategic location'],
            ['Investor-focused project', 'Retail and office suitability', 'Strong connectivity', 'Professional environment', 'Growth-oriented address'],
            ['Business support nearby', 'Service routes close by', 'Delivery access', 'Customer convenience', 'Long-term commercial value'],
        ],
        'map' => [
            'address' => 'Agra Business Corridor',
            'city' => 'Agra',
            'state' => 'Uttar Pradesh',
            'postal' => '282003',
            'area' => '1050 SqFt',
            'country' => 'India',
        ],
        'mapEmbed' => 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3556.9579156942015!2d78.04414161503943!3d27.210193882974807!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3974f0c97d3db1b3%3A0x0!2sAgra%2C%20Uttar%20Pradesh!5e0!3m2!1sen!2sin!4v1710000000007!5m2!1sen!2sin',
    ],
    'padamdeep-tower' => [
        'name' => 'Padamdeep Tower',
        'slug' => 'padamdeep-tower',
        'pageTitle' => 'Padamdeep Tower - BM Real Estate',
        'category' => 'Office',
        'detailPage' => 'property-details/padamdeep-tower.php',
        'heroImage' => 'images/featured-properties/padamdeep-tower.png',
        'galleryImages' => [
            'images/featured-properties/padamdeep-tower.png',
            'images/banner/banner-property-1.jpg',
            'images/banner/banner-property-2.jpg',
            'images/featured-properties/Vrindavan-scaled.jpg',
        ],
        'summary' => 'A commercial tower concept designed for modern business spaces in a prime location.',
        'description' => [
            'Padamdeep Tower Agra is an upcoming commercial development under construction, created to provide business spaces with good access and strong visibility.',
            'The project suits investors and operators looking for a straightforward commercial address in a growing area.',
        ],
        'location' => 'Prime Commercial Zone, Agra',
        'price' => 'On request',
        'priceSuffix' => '',
        'beds' => '2',
        'baths' => '2',
        'sqft' => '980',
        'overviewId' => 'PT-618',
        'nearby' => 'Near business activity, roadway access, and commercial support services.',
        'overview' => [
            ['icon' => 'icon-house-line', 'label' => 'ID', 'value' => 'PT-618'],
            ['icon' => 'icon-sliders-horizontal', 'label' => 'Type', 'value' => 'Office'],
            ['icon' => 'icon-garage', 'label' => 'Garages', 'value' => '1'],
            ['icon' => 'icon-bed1', 'label' => 'Bedrooms', 'value' => '2 Rooms'],
            ['icon' => 'icon-bathtub', 'label' => 'Bathrooms', 'value' => '2 Rooms'],
            ['icon' => 'icon-crop', 'label' => 'Land Size', 'value' => '980 SqFt'],
            ['icon' => 'icon-hammer', 'label' => 'Year Built', 'value' => '2024'],
            ['icon' => 'icon-ruler', 'label' => 'Size', 'value' => '980 SqFt'],
        ],
        'details' => [
            ['label' => 'ID', 'value' => '#PT-618'],
            ['label' => 'Beds', 'value' => '2'],
            ['label' => 'Price', 'value' => 'On request'],
            ['label' => 'Year built', 'value' => '2024'],
            ['label' => 'Size', 'value' => '980 sqft'],
            ['label' => 'Type', 'value' => 'Office'],
            ['label' => 'Rooms', 'value' => '8'],
            ['label' => 'Status', 'value' => 'For sale'],
            ['label' => 'Baths', 'value' => '2'],
            ['label' => 'Garage', 'value' => '1'],
        ],
        // 'attachments' => [
        //     ['image' => 'images/home/file-1.png', 'name' => 'Padamdeep-Tower-Brochure.pdf'],
        //     ['image' => 'images/home/file-2.png', 'name' => 'Padamdeep-Tower-Price-List.pdf'],
        // ],
        'features' => [
            ['Tower-style business spaces', 'Professional address', 'Prime road visibility', 'Office-oriented layout', 'Commercial utility'],
            ['Future business demand', 'Easy accessibility', 'Modern working environment', 'Urban growth potential', 'Investment prospects'],
            ['Nearby services', 'Traffic accessibility', 'Public transport reach', 'Client-friendly access', 'Strategic business zone'],
        ],
        'map' => [
            'address' => 'Prime Commercial Zone, Agra',
            'city' => 'Agra',
            'state' => 'Uttar Pradesh',
            'postal' => '282004',
            'area' => '980 SqFt',
            'country' => 'India',
        ],
        'mapEmbed' => 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3556.9579156942015!2d78.04414161503943!3d27.210193882974807!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3974f0c97d3db1b3%3A0x0!2sAgra%2C%20Uttar%20Pradesh!5e0!3m2!1sen!2sin!4v1710000000008!5m2!1sen!2sin',
    ],
];
